name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: ./vis-website

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # This is a combination of
      #   https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
      #   https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Cache Next.js build
          uses: actions/cache@v3
          with:
            path: |
              ${{ steps.yarn-cache-dir-path.outputs.dir }}
              ${{ github.workspace }}/.next/cache
            # Generate a new cache whenever packages or source files change.
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
            # If source files changed but packages didn't, rebuild from a prior cache.
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-


      - name: Build
        run: |
          yarn
          yarn build
          yarn export
        working-directory: ./vis-website

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./vis-website/out
